%% Title
% Program: caclgui.m
% Description: A simple 4 function calculator.
% Author: Christian Vance 
% Version: V1.1


%% Main Figure
%	INIT
fig = figure( 'MenuBar', 'none', ...
	 'ToolBar', 'none', ...
	 'Color', [.280 .280 .280], ...
	 'Name', 'Calculator', ...
	 'NumberTitle', 'off', ...
	 'Resize', 'off', ...
	 'Units', 'points', ...
	 'Position',[20, 30 , 350, 400] );
 
bg = uibuttongroup( fig, ...
					'Visible', 'on', ...
					'Title', 'Button Group Uno', ...
					'Position', [ 20,  30, 350, 400] );

% BUTTONS
pb1 = uicontrol( bg, ...
				'style', 'push', ...
				'String', '1', ...
				'FontSize', 20, ...
				'BackgroundColor', 'white', ...
				'ForegroundColor', 'black', ...
				'Units', 'points', ...
				'Position', [ 50, 50, 100, 100 ] );
			
				
% fig  = uifigure( 'MenuBar', 'none', ...
% 	 'ToolBar', 'none', ...
% 	 'Color', [.280 .280 .280], ...
% 	 'Name', 'Calculator', ...
% 	 'NumberTitle', 'off', ...
% 	 'Resize', 'off', ...
% 	 'Units', 'points', ...
% 	 'Position',[20, 30 , 350, 400] );
%  
%  
%  %% Button Group/Buttons 
%  bg = uibuttongroup( 'Visible', 'off', ...
% 	 'BackgroundColor', [0 0 0], ...
% 	 'Position', [50, 45, 200, 200], ...
% 	 'BorderType', 'line' );
%  
 
